name: Build & Push Docker Image

# Only run this workflow on pushing any new tag
on:
  push:
    tags:
      - '**'
jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    steps:
    - name: Set env
      run: echo "TAG_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - uses: actions/checkout@v2
      with:
        path: 'server'
    - uses: actions/checkout@v2
      with:
        repository: 'TryAventum/compose'
        path: 'compose'

    - name: Copy files to server folder of the compose
      run: cp -a server/. compose/server/

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and tag image
      run: docker build -t aventum/server:${{ env.TAG_VERSION }} -t aventum/server:latest ${{ env.GITHUB_WORKSPACE }}/compose/server
      
    - name: Push to image registry
      run: |
        docker push aventum/server:latest
        docker push aventum/server:${{ env.TAG_VERSION }}

